version: '3'
services:

  typeorm_aios_informix:
    image: ibmcom/informix-developer-database:12.10.FC11DE
    environment:
    - LICENSE=accept
    privileged: true
    ports:
    - 127.0.0.1:9088:9088
    - 127.0.0.1:9089:9089
    tty: true
    shm_size: 1gb

  aios:
    image: thinkbaer/aios:0.5.0
    container_name: typeorm_aios
    ports:
    - 127.0.0.1:8118:8118
    network_mode: host
