version: '3'
services:

  informix:
    image: ibmcom/informix-developer-database
    container_name: typeorm_aios_informix
    environment:
    - LICENSE=accept
    privileged: true
    ports:
    - 127.0.0.1:9088:9088
    - 127.0.0.1:9089:9089
    tty: true
    shm_size: 256mb

  aios:
    image: thinkbaer/aios:0.3.0
    container_name: typeorm_aios
    ports:
    - 127.0.0.1:8118:8118
    links:
      - informix
