version: '3'
services:

  informix:
    image: ibmcom/informix-developer-database
    environment:
    - LICENSE=accept
    privileged: true
    ports:
    - 127.0.0.1:9088:9088
    - 127.0.0.1:9089:9089
    tty: true

  aios:
    image: thinkbaer/aios:0.2.0
    ports:
    - 127.0.0.1:8118:8118
    links:
      - informix
